Repository X-DataInitiative/tick, pull requests merged in 2019-03, with the labels that each got.

#250 Added serialize function to Model hawkes
  lib/cpp-test/hawkes/model/hawkes_models_gtest.cpp
  lib/cpp/survival/model_sccs.cpp
  lib/include/tick/array/abstractarray1d2d.h
  lib/include/tick/array/array.h
  lib/include/tick/array/array2d.h
  lib/include/tick/array/basearray.h
  lib/include/tick/array/basearray2d.h
  lib/include/tick/array/sarray.h
  lib/include/tick/array/sarray2d.h
  lib/include/tick/array/sbasearray2d.h
  lib/include/tick/base/debug.h
  lib/include/tick/hawkes/model/base/model_hawkes.h
  lib/include/tick/hawkes/model/base/model_hawkes_leastsq.h
  lib/include/tick/hawkes/model/base/model_hawkes_list.h
  lib/include/tick/hawkes/model/base/model_hawkes_loglik.h
  lib/include/tick/hawkes/model/base/model_hawkes_loglik_single.h
  lib/include/tick/hawkes/model/base/model_hawkes_single.h
  lib/include/tick/hawkes/model/list_of_realizations/model_hawkes_expkern_leastsq.h
  lib/include/tick/hawkes/model/list_of_realizations/model_hawkes_expkern_loglik.h
  lib/include/tick/hawkes/model/list_of_realizations/model_hawkes_sumexpkern_leastsq.h
  lib/include/tick/hawkes/model/list_of_realizations/model_hawkes_sumexpkern_loglik.h
  lib/include/tick/hawkes/model/model_hawkes_expkern_leastsq_single.h
  lib/include/tick/hawkes/model/model_hawkes_expkern_loglik_single.h
  lib/include/tick/hawkes/model/model_hawkes_sumexpkern_leastsq_single.h
  lib/include/tick/hawkes/model/model_hawkes_sumexpkern_loglik_single.h
  lib/include/tick/survival/model_coxreg_partial_lik.h
  lib/include/tick/survival/model_sccs.h
  lib/swig/tick/survival/model_coxreg_partial_lik.i
  lib/swig/tick/survival/model_sccs.i
  lib/swig/tick/survival/survival_module.i
  sh/configure_env.sh
  tick/survival/build/__init__.py
  tick/survival/model_sccs.py
  tick/survival/tests/model_coxreg_partial_lik_test.py
  tick/survival/tests/model_sccs_test.py
  tools/travis/docker_run.sh
Labels: enhancement, ready

#343 Update SimuSCCS doc
  tick/survival/simu_sccs.py
Labels: enhancement, examples or doc

#348 add/fix serialization for proxs
  lib/include/tick/prox/prox_group_l1.h
  lib/include/tick/prox/prox_with_groups.h
  lib/swig/tick/base/serialization.i
  lib/swig/tick/prox/prox_binarsity.i
  lib/swig/tick/prox/prox_elasticnet.i
  lib/swig/tick/prox/prox_equality.i
  lib/swig/tick/prox/prox_group_l1.i
  lib/swig/tick/prox/prox_l1w.i
  lib/swig/tick/prox/prox_l2.i
  lib/swig/tick/prox/prox_l2sq.i
  lib/swig/tick/prox/prox_module.i
  lib/swig/tick/prox/prox_positive.i
  lib/swig/tick/prox/prox_slope.i
  lib/swig/tick/prox/prox_tv.i
  lib/swig/tick/prox/prox_zero.i
  tick/solver/tests/serializing_test.py
Labels: bug, enhancement
